# CI code is based on
# https://github.com/nihui/realsr-ncnn-vulkan/blob/master/.github/workflows/release.yml
# Modified in here for newer vulkan
# https://github.com/onuralpszr/realsr-ncnn-vulkan/blob/vulkan-ci-version/.github/workflows/CI.yml


name: Windows Dev Build
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  APPLICATION_NAME: gfpgan-ncnn-vulkan
  VULKAN_SDK_VERSION: "1.4.357.0"
  OPENCV_VERSION: "4.8.0"

jobs:
  dev-build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "VulkanSDK"
        key: VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer
    - name: cache-opencv
      id: cache-opencv
      uses: actions/cache@v4
      with:
        path: "OpenCV"
        key: opencv-${{ env.OPENCV_VERSION }}-windows
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VERSION }}/windows/vulkansdk-windows-X64-${{ env.VULKAN_SDK_VERSION }}.exe?Human=true -OutFile VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe
        .\VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe --root "$(pwd)\VulkanSDK" --accept-licenses --default-answer --confirm-command install
    - name: install opencv
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://github.com/opencv/opencv/releases/download/${{ env.OPENCV_VERSION }}/opencv-${{ env.OPENCV_VERSION }}-windows.exe -OutFile opencv-${{ env.OPENCV_VERSION }}-windows.exe
        7z x -aoa ./opencv-${{ env.OPENCV_VERSION }}-windows.exe -oOpenCV
    - name: build
      run: |
        $env:OpenCV_DIR="$(pwd)/OpenCV/opencv/build"
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake -A x64 ../src > cmake_log.txt 2>&1
        cmake --build . --config Release -j 2 > build_log.txt 2>&1
    - name: push logs on failure
      if: failure()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b build-debug
        mkdir -p debug-logs
        cp build/cmake_log.txt debug-logs/cmake_log.txt
        cp build/build_log.txt debug-logs/build_log.txt
        git add debug-logs/
        git commit -m "chore: add build debug logs [skip ci]"
        git push origin build-debug --force
