name: release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  APPLICATION_NAME: gfpgan-ncnn-vulkan
  VULKAN_SDK_VERSION: "1.3.268.0"
  OPENCV_VERSION: "4.8.0"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
      PACKAGENAME: gfpgan-ncnn-vulkan-${{ github.ref_name || 'dev' }}-ubuntu
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "${{ env.VULKAN_SDK_VERSION }}"
        key: vulkansdk-linux-x86_64-${{ env.VULKAN_SDK_VERSION }}
    - name: setup-vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VERSION }}/linux/vulkansdk-linux-x86_64-${{ env.VULKAN_SDK_VERSION }}.tar.xz?Human=true -O vulkansdk-linux-x86_64-${{ env.VULKAN_SDK_VERSION }}.tar.xz
        tar -xf vulkansdk-linux-x86_64-${{ env.VULKAN_SDK_VERSION }}.tar.xz
        rm -rf ${{ env.VULKAN_SDK_VERSION }}/source ${{ env.VULKAN_SDK_VERSION }}/samples
        find ${{ env.VULKAN_SDK_VERSION }} -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: Build
      run: |
        sudo apt update
        sudo apt install libopencv-dev python3-opencv -y
        export VULKAN_SDK=`pwd`/${{ env.VULKAN_SDK_VERSION }}/x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2
    - name: download models
      run: |
        wget -q https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/releases/download/v0.0.1-models/GFPGAN-ncnn-models.zip
    - name: package
      run: |
        mkdir -p ${{ env.PACKAGENAME }}/models
        cp README.md LICENSE ${{ env.PACKAGENAME }}
        cp build/gfpgan-ncnn-vulkan ${{ env.PACKAGENAME }}
        strip -g ${{ env.PACKAGENAME }}/gfpgan-ncnn-vulkan
        unzip -q GFPGAN-ncnn-models.zip -d ${{ env.PACKAGENAME }}/models
        zip -9 -r ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip

  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: gfpgan-ncnn-vulkan-${{ github.ref_name || 'dev' }}-windows
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v4
      with:
        path: "VulkanSDK"
        key: VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer
    - name: cache-opencv
      id: cache-opencv
      uses: actions/cache@v4
      with:
        path: "OpenCV"
        key: opencv-${{ env.OPENCV_VERSION }}-windows
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_SDK_VERSION }}/windows/VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe?Human=true -OutFile VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe
        .\VulkanSDK-${{ env.VULKAN_SDK_VERSION }}-Installer.exe --root "$(pwd)\VulkanSDK" --accept-licenses --default-answer --confirm-command install
    - name: install opencv
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://github.com/opencv/opencv/releases/download/${{ env.OPENCV_VERSION }}/opencv-${{ env.OPENCV_VERSION }}-windows.exe -OutFile opencv-${{ env.OPENCV_VERSION }}-windows.exe
        7z x -aoa ./opencv-${{ env.OPENCV_VERSION }}-windows.exe -oOpenCV
    - name: Build
      run: |
        $env:OpenCV_DIR="$(pwd)/OpenCV/opencv/build"
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake -A x64 ../src
        cmake --build . --config Release -j 2
    - name: download models
      run: |
        Invoke-WebRequest -Uri https://github.com/onuralpszr/GFPGAN-ncnn-vulkan/releases/download/v0.0.1-models/GFPGAN-ncnn-models.zip -OutFile GFPGAN-ncnn-models.zip
    - name: package
      run: |
        mkdir ${{ env.PACKAGENAME }}
        mkdir ${{ env.PACKAGENAME }}/models
        cp README.md ${{ env.PACKAGENAME }}
        cp LICENSE ${{ env.PACKAGENAME }}
        cp build/Release/gfpgan-ncnn-vulkan.exe ${{ env.PACKAGENAME }}
        cp OpenCV/opencv/build/x64/vc16/bin/opencv_world*.dll ${{ env.PACKAGENAME }}
        tar -xf GFPGAN-ncnn-models.zip -C ${{ env.PACKAGENAME }}/models
        7z a -tzip ${{ env.PACKAGENAME }}.zip ${{ env.PACKAGENAME }}
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: ${{ env.PACKAGENAME }}.zip

  release:
    needs: [ubuntu, windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: download
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: create-release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifacts/*/*.zip
